Mine/Django_level_4/learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

# TEMPLATE TAGGING
app_name = "basic_app" # necessary to put if you want to call in html app_name: "name of the app"

urlpatterns = [
    path("other/", views.other, name="other"),
    path("relative/", views.relative_url_templates, name="relative_url_templates"),
]

Mine/Django_level_4/learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path("", views.index, name="index"),
    path("basic_app/", include("basic_app.urls")),
    path('admin/', admin.site.urls),
]

Mine/Django_level_4/learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

Mine/Django_level_4/learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {"text":"Hello World","number":100}
    return render(request,"basic_app/index.htm",context_dict)

def other(request):
    return render(request,"basic_app/other.htm")
    
def relative_url_templates(request):
    return render(request,"basic_app/relative_url_templates.htm")

Mine/Django_level_4/learning_templates/templates/basic_app/base.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

    <title>Base</title>
</head>
<body>
<!-- Nav Bar with links Template tagging-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'index'%}">BRAND</a>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index'%}">Admin </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'basic_app:other'%}">Other  </a>
                    </li>
                </ul>
                  
            </div>
    </nav>
    <div class="container"></div>
        {%block body_block %}
        <!--Anything outside of this will be inherited if you extend!-->
        {%endblock%}
    </div>
</body>
</html>

Mine/Django_level_4/learning_templates/templates/basic_app/index.htm
<!DOCTYPE html>
{% extends "basic_app/base.htm"%}
{% load my_extras %} <!--You have to create a folder called templatetags inside you apps and 2 files: 
                        one of them called __init__.py another one with the name that you are gona load-->
    {%block body_block%}
        <h1>Welcome to index</h1>
        
        <h1>{{text |cut1:"Hello"}}</h1> <!--When you want to insert from function with render and you use | means a filter, I created a filter called cut1 in libary my_extras -->
        <h2>{{number | add:"95"}}</h2>
         
        {%endblock%}

Mine/Django_level_4/learning_templates/templates/basic_app/other.htm
<!DOCTYPE html>
{% extends "basic_app/base.htm"%}
    {%block body_block%}
        <h1>Welcome other</h1>
        <h2>This is an example of template inheritance!</h2>
        {%endblock%}

Mine/Django_level_4/learning_templates/templates/basic_app/relative_url_templates.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>relative</title>
</head>
<body>
        <h1>Welcome to relative url templates</h1>
        <a href="{% url 'basic_app:other'%}">the other page</a>
        <a href="{% url 'admin:index'%}">admin</a> <!-- if you want to use this, you need to make the migrations-->
        <a href="{% url 'index'%}">index</a> 
    
</body>
</html>