Mine/Django_level_5/learning_users/basic_app/urls.py
from django.urls import path,include
from basic_app import views

# TEMPLATE TAGGING
app_name = "basic_app" # necessary to put if you want to call in html app_name: "name of the app"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("user_login/", views.user_login, name="user_login"),


]

Mine/Django_level_5/learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path("", views.index, name="index"),
    path("logout/", views.user_logout, name="logout"),

    path('admin/', admin.site.urls),
    path("basic_app/",include("basic_app.urls"))
    
]

Mine/Django_level_5/learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete=models.CASCADE)
    #additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to="profile_pics",blank=True) #When user upload a picture,this picture is going o 

    def __str__(self):
        return self.user.username

Mine/Django_level_5/learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

Mine/Django_level_5/learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm
#Loguin
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

#any name in the import should be used


# Create your views here.

def index(request):
    return render(request,"basic_app/index.htm")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
        
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            #double chek
            if "profile_pic" in request.FILES:
                profile.profile_pic = request.FILES["profile_pic"]
            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,"basic_app/registration.htm",
                            {'user_form':user_form,
                                'profile_form':profile_form,
                                'registered':registered})


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username') # name form
        password = request.POST.get('password') # name form

        user = authenticate(username=username,password=password)

        if user: 
            if user.is_active:
                login(request,user)
                print("Succesful")
                return HttpResponseRedirect(reverse("index"))
            else:
                return HttpResponse("Account no active")
        else:
            print("Someone tried to login and failed!")
            print("Username:{} and password {}".format(username,password))
            return HttpResponse("invalid login detailes supplied")
    else:
        return render(request,"basic_app/login.htm",{})

Mine/Django_level_5/learning_users/templates/basic_app/base.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <title>base</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="navbar-nav">
            <li>
                <a class="navbar-brand" href="{% url 'index'%}">DJANGO</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index'%}">Admin </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'basic_app:register'%}">Registration</a>
            </li>

        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout </a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login </a>
            </li>
        {% endif %}


        </ul>
    </nav>    
    <div class="container">
        {%block body_block%}
        {%endblock body_block%}
    </div>
</body>
</html>

Mine/Django_level_5/learning_users/templates/basic_app/index.htm
{% extends "basic_app/base.htm" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level 5</h1>
</div>
{%endblock%}

Mine/Django_level_5/learning_users/templates/basic_app/login.htm
{% extends "basic_app/base.htm" %}
{% block body_block %}
<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'basic_app:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username: </label>
        <input type="text" name="username" placeholder="Enter username">

        <label for="password">Password: </label>
        <input type="password" name="password" >

        <input type="submit" name="" value="Login">

    </form>
</div>
{% endblock %}

Mine/Django_level_5/learning_users/templates/basic_app/registration.htm
{% extends "basic_app/base.htm" %}
{% load staticfiles %}

{% block body_block %}
<div class="jumbotron">
    {% if registered %}
    <h1>Thank you for registering</h1>
    {%else%}
        <h1>Register here</h1>
        <h3>Fill out the form</h3>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p}}
            {{ profile_form.as_p}}
            <input type="submit" name="" value="Register" >
        </form>

    {%endif%}
</div>
{% endblock %}